const keys = [
  'Backquote', 'Digit1', 'Digit2', 'Digit3', 'Digit4', 'Digit5', 'Digit6', 'Digit7', 'Digit8', 'Digit9', 'Digit0', 'Minus', 'Equal',
  'Backspace', 'Tab', 'KeyQ', 'KeyW', 'KeyE', 'KeyR', 'KeyT', 'KeyY', 'KeyU', 'KeyI', 'KeyO', 'KeyP', 'BracketLeft', 'BracketRight', 'Backslash',
  'Delete', 'CapsLock', 'KeyA', 'KeyS', 'KeyD', 'KeyF', 'KeyG', 'KeyH', 'KeyJ', 'KeyK', 'KeyL', 'Semicolon', 'Quote', 'Enter', 'ShiftLeft', 'KeyZ',
  'KeyX', 'KeyC', 'KeyV', 'KeyB', 'KeyN', 'KeyM', 'Comma', 'Period', 'Slash', 'ArrowUp', 'ShiftRight', 'ControlLeft', 'OS', 'AltLeft', 'Space', 'AltRight',
  'ArrowLeft', 'ArrowDown', 'ArrowRight', 'ControlRight'];

const keysFuncStatus = {
  Backquote: false,
  Digit1: false,
  Digit2: false,
  Digit3: false,
  Digit4: false,
  Digit5: false,
  Digit6: false,
  Digit7: false,
  Digit8: false,
  Digit9: false,
  Digit0: false,
  Minus: false,
  Equal: false,
  KeyQ: false,
  KeyW: false,
  KeyE: false,
  KeyR: false,
  KeyT: false,
  KeyY: false,
  KeyU: false,
  KeyI: false,
  KeyO: false,
  KeyP: false,
  BracketLeft: false,
  BracketRight: false,
  Backslash: false,
  KeyA: false,
  KeyS: false,
  KeyD: false,
  KeyF: false,
  KeyG: false,
  KeyH: false,
  KeyJ: false,
  KeyK: false,
  KeyL: false,
  Semicolon: false,
  Quote: false,
  KeyZ: false,
  KeyX: false,
  KeyC: false,
  KeyV: false,
  KeyB: false,
  KeyN: false,
  KeyM: false,
  Comma: false,
  Period: false,
  Slash: false,
  Space: false,
  CapsLock: true,
  ArrowUp: true,
  ArrowLeft: true,
  ArrowDown: true,
  ArrowRight: true,
  ShiftRight: true,
  ControlLeft: true,
  ControlRight: true,
  OS: true,
  AltLeft: true,
  AltRight: true,
  Enter: true,
  ShiftLeft: true,
  Backspace: true,
  Delete: true,
  Tab: true,
};

const keysWidth = {
  Backquote: 'short',
  Digit1: 'short',
  Digit2: 'short',
  Digit3: 'short',
  Digit4: 'short',
  Digit5: 'short',
  Digit6: 'short',
  Digit7: 'short',
  Digit8: 'short',
  Digit9: 'short',
  Digit0: 'short',
  Minus: 'short',
  Equal: 'short',
  Backspace: 'very-long',
  Delete: 'long',
  Tab: 'long',
  KeyQ: 'short',
  KeyW: 'short',
  KeyE: 'short',
  KeyR: 'short',
  KeyT: 'short',
  KeyY: 'short',
  KeyU: 'short',
  KeyI: 'short',
  KeyO: 'short',
  KeyP: 'short',
  BracketLeft: 'short',
  BracketRight: 'short',
  Backslash: 'short',
  CapsLock: 'very-long',
  KeyA: 'short',
  KeyS: 'short',
  KeyD: 'short',
  KeyF: 'short',
  KeyG: 'short',
  KeyH: 'short',
  KeyJ: 'short',
  KeyK: 'short',
  KeyL: 'short',
  Semicolon: 'short',
  Quote: 'short',
  Enter: 'very-long',
  ShiftLeft: 'very-long',
  KeyZ: 'short',
  KeyX: 'short',
  KeyC: 'short',
  KeyV: 'short',
  KeyB: 'short',
  KeyN: 'short',
  KeyM: 'short',
  Comma: 'short',
  Period: 'short',
  Slash: 'short',
  ArrowUp: 'short',
  ShiftRight: 'very-long',
  ControlLeft: 'long',
  OS: 'long',
  AltLeft: 'long',
  Space: 'space-long',
  AltRight: 'long',
  ArrowLeft: 'short',
  ArrowDown: 'short',
  ArrowRight: 'short',
  ControlRight: 'long',
};

export { keys, keysFuncStatus, keysWidth };
